### ISSUE TITLE
Not working in Python 3

### ISSUE THREAD

**Issue by Sopor** [drivard/update-noip#3]
It would be nice if your script also worked in Python 3. Now i only get:

```
  File "update_noip.py", line 40
    print r.status_code  # if 200 this means the page was reached
          ^
SyntaxError: Missing parentheses in call to 'print'
```

And maybe also stop the script if these are empty:
    HOSTNAME = ""  # noip.com hostname
    USERNAME = ""  # noip.com username
    PASSWORD = ""  # noip.com password
Instead of only showing this:
401
badauth

401
badauth

**Comment by suntong** [comment]
Does it work for Python 2?

Would one still get the "expiration" notice on a monthly basis even the IPs are updated weekly?

**Comment by Sopor** [comment]
I don't believe this script works anymore because you now need to login to no-ip and press buttons, one for every host. Even if you force an IP update you still get an email that your host will expire in 7 days. I manage to find a python script that use 'mechanize' but no-ip have changed their site so it won't work anymore. I don't know if you can get it to work, if you are interested?

**Comment by suntong** [comment]
Yeah, I don't think this script will work either, to get rid of the annoying monthly expiration notice, and I've confirmed it after asking the above question.

**Comment by Sopor-** [comment]
This [script](http://www.stevesprojects.com/?p=106) should work after it has been modified. I believe it is needed CSRF and requests to work. It should work if using the [old ](https://www.noip.com/members/dns/)site instead of the [new](https://my.noip.com/#!/dynamic-dns). No captcha or other verification services. You only need to press `Modify` and `Update Host`

**Comment by suntong** [comment]
Were you able to make it working, or you were thinking it should work with only slightly changes?

**Comment by Sopor** [comment]
I never got it to work but i'm far far away from being a python expert. Nothing has been changed on the old site as you still can login and only press `Update Host` and you have 30 new days before it expired. I believe they have changed the way you login and that is why it won't work. But again, i'm not an expert in python.

**Comment by suntong** [comment]
Thx. 

So basically my question and the conclusion is, still, no script will work anymore to get rid of the annoying monthly expiration notice

> because you now need to login to no-ip and press buttons, one for every host. Even if you force an IP update you still get an email that your host will expire in 7 days. 

@Sopor- , if you don't mind the monthly manual login, check out

ddclient - address updating utility for dynamic DNS services

which works for no-ip still. 

Description-en: address updating utility for dynamic DNS services
 This package provides a client to update dynamic IP addresses with
 several dynamic DNS service providers, such as DynDNS.com.
 .
 This makes it possible to use a fixed hostname (such as
 myhost.dyndns.org) to access a machine with a dynamic IP address.
 .
 This client supports both dynamic and (near) static services, as  well as
 MX record and alternative name management. It caches the address, and
 only attempts the update when it has changed.

Homepage: http://ddclient.sf.net

**Comment by Sopor** [comment]
@suntong But this script did that using 'mechanize', so a python expert should be able to fix this quite easy i believe. You only need to find him :)

About the client i run `DNS Update Client (DUC)` and i also use `pfsense` and on Linux i use a script. All except DUC did a forced update on NO-IP to prevent these emails but that is not enough because you need to login to reset the 30 days.

**Comment by suntong** [comment]
Oh, yeah, you're right. I forgot why I was here in the first place, :-). 

I believe this script was coded for the old site instead of the new site though.

**Comment by Sopor** [comment]
@suntong If you still want to reset the counter on no-ip you should be able to use this
```
#!/usr/bin/python
 
import sys, mechanize, cookielib, re, os

login_site = "https://www.noip.com/login/"
host_ids = ["<first>","<second>","<third>"] 
username = "<username>"
password = "<password>"
update_site = "https://www.noip.com/members/dns/host.php?host_id="
logout_url = "https://www.noip.com/login/?logout=1"
 

br = mechanize.Browser()
br.set_handle_equiv(True)
br.set_handle_redirect(True)
br.set_handle_referer(True)
br.set_handle_robots(False)
cj = cookielib.LWPCookieJar()
br.set_cookiejar(cj)
br.set_handle_refresh(mechanize._http.HTTPRefreshProcessor(), max_time=1)
br.addheader = [("User-agent", "Firefox")]
 
print "Connecting to %s"%login_site
br.open(login_site)
br.select_form(nr=0)
br.form['username'] = username
br.form['password'] = password
print "Logging in..."
br.submit()
print "Currently on page:", br.title()

for host_id in host_ids:
	print "Updating host ID:", host_id
	print update_site+str(host_id)
	br.open(update_site+str(host_id))
	br.select_form(nr=0)
	br.submit()
	print "Currently on page:", br.title()

print "Done, logging out."
br.open(logout_url) 
```
Python 2.x and you need to install
1. `sudo apt-get install python-setuptools python-dev build-essential`
2. `sudo easy_install mechanize`

**Comment by suntong** [comment]
OMG, Thanks a lot @Sopor-! 

I've given up the no-ip for its annoying monthly expiration notice and actions. 
But I'll sure pick it up again thanks to your new script, :-)

**Comment by suntong** [comment]
Just FTA, in case some one reading this get the following like me:

```
Traceback (most recent call last):
  File "./no-ip.py", line 3, in <module>
    import sys, mechanize, cookielib, re, os
ImportError: No module named mechanize
```

The fix is at https://stackoverflow.com/questions/14295680/

I.e., under Ubuntu, it is

    sudo chmod -R ugo+rX  /usr/local/lib/python2.7/dist-packages/

**Comment by suntong** [comment]
@Sopor-, what should I put in the `host_ids = ["<first>","<second>","<third>"] `?

I put my actual domain name, `myown.ddns.net`, but having successfully run it, its IP and last update time are still not change when verifyint again from the web site. Here is my run log:

```
$ no-ip.py
Connecting to https://www.noip.com/login/
Logging in...
Currently on page: My No-IP
Updating host ID: myown.ddns.net
https://www.noip.com/members/dns/host.php?host_id=myown.ddns.net
Currently on page: No-IP Members Portal: Managed DNS : Add a host
Done, logging out.
```

Looks good to me. Please help. thx.

**Comment by suntong** [comment]
Oh, found the correct ID to use, however, having successfully run it, its IP and last update time are still not change when verifying again from the web site.

**Comment by suntong** [comment]
Found the problem, after getting to the 

https://www.noip.com/members/dns/host.php?host_id=xxxx

page, there is _one more step_ -- one more button "**Update Host**" to click. I'll see what I can do tomorrow...

**Comment by suntong** [comment]
OK, I gave up, things are more complicated than I thought. 

The script was coded for the old site instead of the new site, but I found the new site/request is more easier to handle than the old one, but I can't do it myself, as i'm far far away from knowing python at all. 

I'm learning JavaScript/Nodejs now, and am hoping that it'd be easier to do in Nodejs instead. will post back...

**Comment by Sopor** [comment]
What is your problem @suntong ? It works for me.

**Comment by suntong** [comment]
You meant the script or the actual result works for you? 

my problem: _"having successfully run it, its IP and last update time are still not change when verifyint again from the web site"_

**Comment by suntong** [comment]
you need to view and check from the _new site_, which tell you when was _last updated_, etc.

**Comment by Sopor** [comment]
Did you do a refresh of the no-ip page?

**Comment by suntong** [comment]
yeah, are you verifying from the new site?

**Comment by Sopor** [comment]
@suntong Look at [this](https://sprend.com/download.htm?C=85e89bab7a0a43318afe1d00ae57049c) video and you will see it change the days from 28 to 29 days.
`Note: This file will only be valid for some time, then it will expire.`

**Comment by suntong** [comment]
Got it. Now I've seen with my own eyes that it is _indeed_ working, thanks to your video. 

So strange. hmm..., if  you visit the update url _manually_, i.e., the

https://www.noip.com/members/dns/host.php?host_id=xxxx

page, do you see if there is one more step -- one more button "Update Host" to click? -- I manually changed mine to a fake IP, `1.2.3.4` from web and it wasn't get updated no matter what. 

Maybe noip is doing different things for IPs from different part of the world... Anyway, glad that it is working for you, and thanks for all the helps you've given me. 

cheers

**Comment by suntong** [comment]
Ah, cross that, no need answer, I saw that the script is indeed doing a `submit()` on the update url. thanks again for all the helps.

cheers

**Comment by Sopor** [comment]
Yeah, the script will not update the IP address, only the expire date.

**Comment by suntong** [comment]
Ah, finally it is working for me!!! Maybe previously my caching proxy server is refusing to send me a updated page even I click "refresh" on browser. After forcing a refresh, I'm seeing the update now. 

BTW, I also changed the code to:

        print "Currently on page:", br.geturl()

which _assured_ me that all the form parameters are sent correctly. 

I'm so happy, thanks again for all the helps you've given me.

**Comment by suntong** [comment]
this can be close now. :-)

**Comment by Sopor** [comment]
NOIP has change the way you can confirm a hostname. You can now only confirm your hostname if it is within 7 days of expiring.

Here is a working script for Python 3:

```
#!/usr/bin/python
 
import sys, mechanize, http.cookiejar, re, os

import datetime
now = datetime.datetime.now()

login_site = "https://www.noip.com/login/"
host_ids = ["","",""] 
username = ""
password = ""
update_site = "https://www.noip.com/members/dns/host.php?host_id="
logout_url = "https://www.noip.com/login/?logout=1"

# This script won't update the ddns, it will only reset the day counter.
# UPDATE: NOIP has change the way you can confirm a hostname. You can now only confirm your hostname if it is within 7 days of expiring.

# To get the host_ids you have to login and go to My Services / DNS Records https://www.noip.com/members/dns
# and click on Modify and you should see the host_id in the URL.
# Modify the amount of host_ids you use so it fits your needs and remove those you don't use.
# If you only have one ddns it should look like this on line 6: host_ids = ["12345678"]

br = mechanize.Browser()
br.set_handle_equiv(True)
br.set_handle_redirect(True)
br.set_handle_referer(True)
br.set_handle_robots(False)
cj = http.cookiejar.LWPCookieJar()
br.set_cookiejar(cj)
br.set_handle_refresh(mechanize._http.HTTPRefreshProcessor(), max_time=1)
br.addheader = [("User-agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0")]

print("Connecting to %s"%login_site)
br.open(login_site)
br.select_form(nr=0)
br.form['username'] = username
br.form['password'] = password
print("Logging in...")
br.submit()
print("Currently on page:", br.title())

for host_id in host_ids:
	print("Updating host ID:", host_id)
	print(update_site+str(host_id))
	br.open(update_site+str(host_id))
	br.select_form(nr=0)
	br.submit()
	print("Currently on page:", br.title())

print("Done, logging out.")
br.open(logout_url)
print (now.strftime("%Y-%m-%d %H:%M\n\n"))
```

**Comment by suntong** [comment]
Holly sh*t, pardon my French, but I just can't express how grateful I am. 

Yes I got my hostname expiring warning and hostname expired message recently too, and I haven't figure out what the problem yet. 

Thanks for the solution @Sopor!

**Comment by suntong** [comment]
> UPDATE: NOIP has change the way you can confirm a hostname. You can now only confirm your hostname if it is within 7 days of expiring.

Just to be 100% clear, the only change we the script end user need to do, apart from changing the script as above, is that we need a way to make sure the script is called within 7 days of hostname being expiring, right?

**Comment by suntong** [comment]
I.e., would a cron job of `*/7` that runs every 7 days works, or it has to be  `*/6`?

**Comment by Sopor** [comment]
I run it twice a week to be sure (Monday and Thursday) . You never know if the site has connection issues or something else make it fail.

I don't know if it make any difference or not, but i run it randomly to not make NOIP detect it is a cron job:
```
perl -le 'sleep rand 7200' && python3 /path/noip_no_exp.py
```

7200 is the same as 2 hours. So, if you set the cron job to run at 2:00 it will randomly start the python script between 2:00 and 4:00.

**Comment by suntong** [comment]
Aha, wonderful tip! Thanks again!

**Comment by Sopor** [comment]
@suntong I have tested it today and it will not reset the days. The script need modifications and that is way over my head :(

**Comment by suntong** [comment]
Thanks for the update, that's really sad, 😢😢😢

**Comment by Sopor** [comment]
@suntong I have found a script that will work. You should be able to find my comment and do as i did to get it to work:
`https://github.com/loblab/noip-renew`

**Comment by suntong** [comment]
👍👍👍🙏🙏🙏
